services:
  - type: web
    name: django-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn djangoproj.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true